# Generated by Django 3.2.9 on 2022-04-30 03:09

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'ajuste',
                'verbose_name_plural': 'ajustes',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='almacen')),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='area')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.almacen')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cliente')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subtotalpiezas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'devolucion',
                'verbose_name_plural': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(max_length=255)),
                ('fecha_cierre', models.DateField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subtotalpiezas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Realizado', 'Realizado')], default='Programado', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='egresos')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientee', to='index.cliente')),
            ],
            options={
                'verbose_name': 'egreso',
                'verbose_name_plural': 'egresos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa', validators=[index.models.validate_image])),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subtotalpiezas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Realizado', 'Realizado')], default='Programado', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='ingresos')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'iva',
                'verbose_name_plural': 'iva',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('cargo', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personal')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tecnico',
                'verbose_name_plural': 'tecnicos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proveedor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='zona')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.area')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(max_length=255)),
                ('fecha_cierre', models.DateField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subtotalpiezas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Realizado', 'Realizado')], default='Programado', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='traspasos')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinot', to='index.zona')),
                ('procedencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedenciat', to='index.zona')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablet', to='index.personal')),
            ],
            options={
                'verbose_name': 'traspaso',
                'verbose_name_plural': 'traspasos',
                'order_with_respect_to': 'fecha_pedido',
            },
        ),
        migrations.CreateModel(
            name='ProductosTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.inventario')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.traspaso')),
            ],
            options={
                'verbose_name': 'producto traspaso',
                'verbose_name_plural': 'productos traspaso',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='ProductosIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.inventario')),
            ],
            options={
                'verbose_name': 'producto ingreso',
                'verbose_name_plural': 'productos ingreso',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='ProductosEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.egreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.inventario')),
            ],
            options={
                'verbose_name': 'producto egreso',
                'verbose_name_plural': 'productos egreso',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='ProductosDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.inventario')),
            ],
            options={
                'verbose_name': 'producto devolucion',
                'verbose_name_plural': 'productos devolucion',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='ProductosAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_registrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad_real', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ajuste')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.inventario')),
            ],
            options={
                'verbose_name': 'producto ajuste',
                'verbose_name_plural': 'productos ajuste',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('iva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.iva')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'order_with_respect_to': 'descripcion',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.zona'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.zona'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedori', to='index.proveedor'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablei', to='index.personal'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='ingreso',
            order_with_respect_to='fecha',
        ),
        migrations.AddField(
            model_name='egreso',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablee', to='index.personal'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='egreso',
            order_with_respect_to='fecha_pedido',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.egreso'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='devolucion',
            order_with_respect_to='created',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablea', to='index.personal'),
        ),
    ]
