# Generated by Django 3.2.9 on 2022-05-05 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_auto_20220505_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajuste',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ajuste',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='cantidad_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='cantidad_registrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.producto'),
        ),
        migrations.AlterField(
            model_name='ajuste',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsablea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductosAjuste',
        ),
    ]
