# Generated by Django 3.2.9 on 2022-05-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220505_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areae', to='index.area'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='traspaso',
            field=models.BooleanField(default=False),
        ),
    ]
