# Generated by Django 3.2.9 on 2022-05-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20220505_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosegreso',
            name='devolucion',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductosDevolucion',
        ),
    ]
