# Generated by Django 3.2.9 on 2022-06-11 19:19

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_empresa_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='zona',
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda',
            field=models.CharField(default='$', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('Pieza', 'Pieza'), ('Kg', 'Kg'), ('Lt', 'Lt'), ('Metro', 'Metro'), ('Caja', 'Caja'), ('Onza', 'Onza'), ('Otro', 'Otro')], default='Pieza', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, size=[100, 100], upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
