# Generated by Django 3.2.9 on 2022-06-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20220613_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='desglosar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='ticket',
            field=models.BooleanField(default=True),
        ),
    ]
