# Generated by Django 3.2.9 on 2022-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20220623_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosegreso',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='productosegreso',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
