# Generated by Django 3.2.9 on 2022-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20220623_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosegreso',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
