# Generated by Django 3.2.9 on 2022-06-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_pagosegreso_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='responsable',
        ),
    ]
