# Generated by Django 4.0.5 on 2024-07-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_remove_ingreso_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personall', to='index.personal'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('Programado', 'Programado'), ('En espera', 'En espera'), ('En proceso', 'En proceso'), ('Atrasado', 'Atrasado'), ('Realizado', 'Realizado')], default='Realizado', max_length=255),
        ),
    ]
