# Generated by Django 4.0.5 on 2024-07-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_alter_cliente_od_esf_alter_cliente_oi_esf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='OD_Cil',
            field=models.CharField(blank=True, default='-0 X 0°', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OI_Cil',
            field=models.CharField(blank=True, default='-0 X 0°', max_length=10, null=True),
        ),
    ]
