# Generated by Django 4.0.5 on 2024-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_alter_cliente_od_cil_alter_cliente_oi_cil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ADD',
            field=models.CharField(blank=True, default='+0.00', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='DIP',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Edad',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OD_Cil',
            field=models.CharField(blank=True, default='-0.00 X 0°', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OD_Esf',
            field=models.CharField(blank=True, default='0.00', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OI_Cil',
            field=models.CharField(blank=True, default='-0.00 X 0°', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OI_Esf',
            field=models.CharField(blank=True, default='0.00', max_length=15, null=True),
        ),
    ]
